#!/usr/bin/env node
/**
 * Generate e2e/acceptance-report.md from the Playwright JSON reporter output
 * (FRG-PROC-010). There is NO hand-authored criteria matrix: every row is
 * derived from a real test — its title names the FRG requirement id(s) it
 * exercises, and its outcome (pass / fail / skipped) comes straight from the
 * run. Skipped-by-design tiers (the live-SAB tier) surface as "skipped".
 *
 * Usage: node acceptance-report.mjs <results.json> <out.md>
 */
import { readFileSync, writeFileSync } from 'node:fs';

const [, , inPath, outPath] = process.argv;
if (!inPath || !outPath) {
  console.error('usage: acceptance-report.mjs <results.json> <out.md>');
  process.exit(2);
}

const ID_RE = /FRG-[A-Z]{2,5}-\d{3}/g;

let report;
try {
  report = JSON.parse(readFileSync(inPath, 'utf8'));
} catch (err) {
  // A missing or unparseable results.json means Playwright crashed / was
  // interrupted before writing a report. Never fail silently and never leave a
  // stale (possibly GREEN) report behind: write an explicit RED report and exit
  // non-zero so run.sh propagates the failure (FRG-PROC-010).
  const red = [
    '# foragerr end-to-end acceptance report',
    '',
    '_Generated by `e2e/scripts/acceptance-report.mjs` (FRG-PROC-010)._',
    '',
    '- **Verdict:** RED',
    '- **Scenarios:** run did not produce results',
    '',
    'The Playwright run produced no parseable `results.json` at ' +
      `\`${inPath}\` (${err.message}). The suite crashed or was interrupted ` +
      'before any scenario outcome was recorded. This report is RED by ' +
      'construction — no scenario outcomes are available.',
    '',
  ];
  writeFileSync(outPath, red.join('\n') + '\n');
  console.error(
    `could not read Playwright results at ${inPath}: ${err.message} — wrote RED report`,
  );
  process.exit(1);
}

/**
 * Recursively collect every spec across nested suites.
 *
 * Outcome derivation is honest — a non-pass shape is NEVER laundered to PASS:
 *   - zero results (never executed)                -> 'notrun'  (verdict RED)
 *   - every result 'skipped'                        -> 'skipped'
 *   - spec.ok === false (final failure)             -> 'fail'
 *   - a 'failed'/'timedOut'/'interrupted' result
 *     that a retry later rescued (spec.ok true)     -> 'flaky'   (surfaced, never silent)
 *   - otherwise                                      -> 'pass'
 */
function collectSpecs(suite, file, acc) {
  const specFile = suite.file ?? file;
  for (const spec of suite.specs ?? []) {
    const statuses = (spec.tests ?? []).flatMap((t) =>
      (t.results ?? []).map((r) => r.status),
    );
    const anyBad = statuses.some(
      (s) => s === 'failed' || s === 'timedOut' || s === 'interrupted',
    );
    let outcome;
    if (statuses.length === 0) outcome = 'notrun';
    else if (statuses.every((s) => s === 'skipped')) outcome = 'skipped';
    else if (spec.ok === false) outcome = 'fail';
    else if (anyBad) outcome = 'flaky';
    else outcome = 'pass';
    const ids = [...new Set(spec.title.match(ID_RE) ?? [])].sort();
    acc.push({ title: spec.title, file: specFile, ids, outcome, statuses });
  }
  for (const child of suite.suites ?? []) collectSpecs(child, specFile, acc);
}

const specs = [];
for (const suite of report.suites ?? []) collectSpecs(suite, suite.file, specs);

const counts = { pass: 0, fail: 0, skipped: 0, flaky: 0, notrun: 0 };
for (const s of specs) counts[s.outcome]++;

// Surface interrupted/timedOut occurrences (both from per-result statuses and
// from report.stats) so an aborted run can never read as clean.
let timedOut = 0;
let interrupted = 0;
for (const s of specs) {
  for (const st of s.statuses) {
    if (st === 'timedOut') timedOut++;
    if (st === 'interrupted') interrupted++;
  }
}
const stats = report.stats ?? {};

const idToOutcomes = new Map();
for (const s of specs) {
  for (const id of s.ids) {
    if (!idToOutcomes.has(id)) idToOutcomes.set(id, new Set());
    idToOutcomes.get(id).add(s.outcome);
  }
}

const badge = {
  pass: 'PASS',
  fail: 'FAIL',
  skipped: 'SKIPPED',
  flaky: 'FLAKY',
  notrun: 'NOT RUN',
};

// GREEN only when every spec is pass or skipped: any fail or not-run is RED.
// Flaky specs (rescued on retry) do NOT block GREEN, but they are never silent
// — GREEN carries an explicit "(N flaky)" annotation and a callout below.
const isRed = counts.fail > 0 || counts.notrun > 0 || interrupted > 0;
let verdict;
if (isRed) verdict = 'RED';
else if (counts.flaky > 0) verdict = `GREEN (${counts.flaky} flaky)`;
else verdict = 'GREEN';

const lines = [];
lines.push('# foragerr end-to-end acceptance report');
lines.push('');
lines.push(
  '_Generated from the Playwright JSON reporter by ' +
    '`e2e/scripts/acceptance-report.mjs` — do not edit by hand (FRG-PROC-010)._',
);
lines.push('');
lines.push(`- **Verdict:** ${verdict}`);
lines.push(
  `- **Scenarios:** ${specs.length} (` +
    `${counts.pass} pass, ${counts.fail} fail, ${counts.skipped} skipped, ` +
    `${counts.flaky} flaky, ${counts.notrun} not run)`,
);
if (counts.flaky > 0) {
  lines.push(
    `- **Flaky:** ${counts.flaky} scenario(s) failed then passed on retry ` +
      '(rescued, but not clean — see the FLAKY rows below).',
  );
}
if (counts.notrun > 0) {
  lines.push(
    `- **Not run:** ${counts.notrun} scenario(s) were never executed — verdict RED.`,
  );
}
if (timedOut > 0 || interrupted > 0) {
  lines.push(
    `- **Aborted results:** ${timedOut} timed out, ${interrupted} interrupted.`,
  );
}
if (typeof stats.unexpected === 'number' && stats.unexpected > 0) {
  lines.push(`- **Reporter stats:** ${stats.unexpected} unexpected failure(s).`);
}
if (report.stats?.startTime) {
  lines.push(`- **Run started:** ${report.stats.startTime}`);
}
if (typeof report.stats?.duration === 'number') {
  lines.push(`- **Duration:** ${(report.stats.duration / 1000).toFixed(1)}s`);
}
lines.push('');
lines.push('## Scenario → requirement coverage');
lines.push('');
lines.push('| Result | Scenario | FRG requirement ids |');
lines.push('| --- | --- | --- |');
for (const s of specs) {
  const title = s.title.replace(/\|/g, '\\|');
  const ids = s.ids.length ? s.ids.join(', ') : '—';
  lines.push(`| ${badge[s.outcome]} | ${title} | ${ids} |`);
}
lines.push('');
lines.push('## Requirement roll-up');
lines.push('');
lines.push('| FRG id | Result |');
lines.push('| --- | --- |');
for (const id of [...idToOutcomes.keys()].sort()) {
  const outcomes = idToOutcomes.get(id);
  const roll = outcomes.has('fail')
    ? 'FAIL'
    : outcomes.has('notrun')
      ? 'NOT RUN'
      : outcomes.has('flaky')
        ? 'FLAKY'
        : outcomes.has('pass')
          ? 'PASS'
          : 'SKIPPED';
  lines.push(`| ${id} | ${roll} |`);
}
lines.push('');
if (counts.fail > 0) {
  lines.push('## Failed scenarios');
  lines.push('');
  for (const s of specs.filter((x) => x.outcome === 'fail')) {
    lines.push(`- **${s.title}** (${s.file})`);
  }
  lines.push('');
}
if (counts.notrun > 0) {
  lines.push('## Not-run scenarios');
  lines.push('');
  for (const s of specs.filter((x) => x.outcome === 'notrun')) {
    lines.push(`- **${s.title}** (${s.file}) — never executed`);
  }
  lines.push('');
}
if (counts.flaky > 0) {
  lines.push('## Flaky scenarios (rescued on retry)');
  lines.push('');
  for (const s of specs.filter((x) => x.outcome === 'flaky')) {
    lines.push(`- **${s.title}** (${s.file}) — statuses: ${s.statuses.join(' → ')}`);
  }
  lines.push('');
}
lines.push('---');
lines.push('');
lines.push(
  '_Hermetic-fixture coverage has known limits: this run does NOT exercise ' +
    'multi-host DDL landing-page parsing/failover, real redirect chains, or ' +
    'real SABnzbd unless the live tier runs. See the **Coverage limits** ' +
    'section of `e2e/README.md` before over-reading this report._',
);

writeFileSync(outPath, lines.join('\n') + '\n');
console.log(
  `acceptance-report.md written: ${verdict} — ` +
    `${counts.pass} pass / ${counts.fail} fail / ${counts.skipped} skipped / ` +
    `${counts.flaky} flaky / ${counts.notrun} not run`,
);
// A not-run / failed / aborted run is a non-zero exit so run.sh can react even
// when Playwright itself somehow returned 0.
if (isRed) process.exit(1);
