#!/usr/bin/env python3
"""Build the foragerr public site (FRG-SITE-001..006).

Renders five static pages — Overview, The Method, Timeline, Trust Center,
Product — from committed repository artifacts only:

  docs/traceability/requirements-registry.md
  docs/traceability/matrix.md
  CHANGELOG.md
  docs/security/risk-register.md
  LICENSE
  git tags

Every displayed fact (count, status, version, date, ID, path, commit) comes
from these sources at build time; templates carry no hand-maintained factual
values (FRG-SITE-001). All sources are loaded and validated, and all pages are
rendered and scanned, before a single output file is written — a failing build
writes nothing.

Usage: python site/build.py [--root REPO] [--out DIR]
"""
import argparse
import html
import re
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path
from string import Template

SITE_DIR = Path(__file__).resolve().parent
ID_RE = re.compile(r'FRG-[A-Z]{2,5}-\d{3}')
RELEASE_RE = re.compile(r'^## \[(v\d+\.\d+\.\d+)\] — (\d{4}-\d{2}-\d{2})\s*$')

# The screenshots the Product page shows, with the README's own captions
# (regenerated by tools/refresh-readme-shots.sh, FRG-PROC-017).
PRODUCT_SHOTS = [
    ('comics-grid.png',
     'The library index: a poster grid of series with cover art, monitored '
     'state, and owned/total issue counts'),
    ('series-detail.png',
     'A series page: cover, publisher and path details, and the issue table '
     'showing owned files and missing issues'),
    ('sources.png',
     'The Sources screen: connecting a Humble Bundle account to import '
     'purchases you already own'),
]


def fail(msg: str) -> 'NoReturn':  # noqa: F821 - py3.11 typing kept light
    print(f'site build failed: {msg}', file=sys.stderr)
    sys.exit(1)


def read_text(path: Path, what: str) -> str:
    if not path.is_file():
        fail(f'missing source artifact: {what} ({path})')
    return path.read_text(encoding='utf-8')


def esc(s: str) -> str:
    return html.escape(s, quote=True)


def inline_md(s: str) -> str:
    """Escape, then render the small inline-markdown subset the sources use."""
    s = esc(s)
    s = re.sub(r'`([^`]+)`', r'<code>\1</code>', s)
    s = re.sub(r'\*\*([^*]+)\*\*', r'<strong>\1</strong>', s)
    s = ID_RE.sub(lambda m: f'<span class="frg-id">{m.group(0)}</span>', s)
    return s


# --- source artifact loaders -------------------------------------------------

def load_config() -> dict:
    cfg = tomllib.loads(read_text(SITE_DIR / 'site.toml', 'site config'))
    for section, key in (('site', 'repo_url'), ('site', 'releases_url'),
                         ('site', 'title'), ('site', 'description'),
                         ('hero', 'exemplar_requirement')):
        if not cfg.get(section, {}).get(key):
            fail(f'site.toml missing [{section}] {key}')
    return cfg


def load_registry(root: Path) -> dict:
    rows = {}
    text = read_text(root / 'docs/traceability/requirements-registry.md',
                     'requirements registry')
    for line in text.splitlines():
        cells = [c.strip() for c in line.strip().strip('|').split('|')]
        if len(cells) >= 5 and ID_RE.fullmatch(cells[0]):
            rows[cells[0]] = {'title': cells[1], 'spec': cells[2],
                              'status': cells[3], 'milestone': cells[4]}
    if not rows:
        fail('requirements registry parsed to zero rows')
    return rows


def load_matrix(root: Path) -> dict:
    rows = {}
    text = read_text(root / 'docs/traceability/matrix.md', 'traceability matrix')
    for line in text.splitlines():
        cells = [c.strip() for c in line.strip().strip('|').split('|')]
        if len(cells) >= 6 and ID_RE.fullmatch(cells[0]):
            split = lambda v: [] if v == '—' else [p.strip() for p in v.split(',')]
            rows[cells[0]] = {'status': cells[1], 'milestone': cells[2],
                              'spec': cells[3], 'tests': split(cells[4]),
                              'commits': split(cells[5])}
    if not rows:
        fail('traceability matrix parsed to zero rows')
    return rows


def load_changelog(root: Path) -> list:
    """Parse CHANGELOG.md into releases: version, date, intro, sections, ids."""
    text = read_text(root / 'CHANGELOG.md', 'CHANGELOG')
    releases, current = [], None
    section = None
    for line in text.splitlines():
        m = RELEASE_RE.match(line)
        if m:
            current = {'version': m.group(1), 'date': m.group(2),
                       'intro': [], 'sections': []}
            releases.append(current)
            section = None
            continue
        if current is None:
            continue
        if line.startswith('### '):
            section = {'name': line[4:].strip(), 'items': []}
            current['sections'].append(section)
            continue
        bucket = section['items'] if section else current['intro']
        if line.startswith('- '):
            bucket.append(line[2:].strip())
        elif line.startswith('  ') and line.strip() and bucket:
            bucket[-1] += ' ' + line.strip()
        elif line.strip() and not section:
            current['intro'].append(line.strip())
        elif line.strip() and section:
            section['items'].append(line.strip())
    if not releases:
        fail('CHANGELOG parsed to zero releases')
    for r in releases:
        blob = ' '.join(r['intro']) + ' '.join(
            i for s in r['sections'] for i in s['items'])
        r['ids'] = sorted(set(ID_RE.findall(blob)))
    return releases


def git_tags(root: Path) -> set:
    out = subprocess.run(['git', 'tag'], capture_output=True, text=True, cwd=root)
    if out.returncode != 0:
        fail(f'git tag failed: {out.stderr.strip()}')
    tags = set(out.stdout.split())
    if not tags:
        fail('repository has no tags')
    return tags


def load_risks(root: Path) -> list:
    risks = []
    text = read_text(root / 'docs/security/risk-register.md', 'risk register')
    for line in text.splitlines():
        cells = [c.strip() for c in line.strip().strip('|').split('|')]
        if len(cells) >= 9 and re.fullmatch(r'RISK-\d{3}', cells[0]):
            risks.append({'id': cells[0], 'desc': cells[1], 'stride': cells[2],
                          'component': cells[3], 'l': cells[4], 'i': cells[5],
                          'status': cells[6]})
    if not risks:
        fail('risk register parsed to zero rows')
    return risks


def license_family(root: Path) -> str:
    text = read_text(root / 'LICENSE', 'LICENSE')
    head = ' '.join(text.split())[:200]
    if 'GNU GENERAL PUBLIC LICENSE' in head and 'Version 3' in head:
        return 'GPL-3.0'
    fail('LICENSE not recognized; refusing to guess a license claim')


def load_banned() -> list:
    lines = read_text(SITE_DIR / 'banned_phrases.txt', 'banned-phrase list')
    return [l.strip() for l in lines.splitlines()
            if l.strip() and not l.startswith('#')]


# --- derived models ----------------------------------------------------------

def exemplar_card(cfg, registry, matrix):
    rid = cfg['hero']['exemplar_requirement']
    if rid not in registry:
        fail(f'exemplar {rid} not in the requirements registry')
    if rid not in matrix:
        fail(f'exemplar {rid} not in the traceability matrix')
    row = matrix[rid]
    if not row['tests'] or not row['commits']:
        fail(f'exemplar {rid} lacks tests or commits in the matrix')
    tests = row['tests'][0] + (f' +{len(row["tests"]) - 1} more'
                               if len(row['tests']) > 1 else '')
    return {
        'id': rid,
        'title': registry[rid]['title'],
        'rows': [
            ('Spec', f'openspec/specs/{row["spec"]}/spec.md'),
            ('Tests', tests),
            ('Commits', ', '.join(row['commits'][:3])),
            ('Status', f'{row["status"]} · {row["milestone"]}'),
        ],
    }


def coverage(registry, matrix):
    live = [rid for rid, r in registry.items() if r['status'] != 'withdrawn']
    traced = [rid for rid in live if matrix.get(rid, {}).get('tests')]
    return len(traced), len(live)


def coverage_breakdown(registry, matrix):
    """Traced-test coverage split by requirement status (FRG-SITE-004)."""
    def bucket(status):
        ids = [r for r, row in registry.items() if row['status'] == status]
        tested = [r for r in ids if matrix.get(r, {}).get('tests')]
        return len(tested), len(ids)
    impl_tested, impl_total = bucket('implemented')
    v_tested, v_total = bucket('verified')
    appr_tested, appr_total = bucket('approved')
    act_tested, act_total = bucket('active')
    return {
        'implemented_tested': impl_tested + v_tested,
        'implemented_total': impl_total + v_total,
        'approved_total': appr_total,
        'active_tested': act_tested,
        'active_total': act_total,
    }


def archive_approvals(root: Path):
    """(archived change count, count with a recorded ## Approval section)."""
    archive = root / 'openspec/changes/archive'
    if not archive.is_dir():
        fail('missing source artifact: openspec change archive '
             f'({archive})')
    changes = sorted(d for d in archive.iterdir() if d.is_dir())
    if not changes:
        fail('openspec change archive is empty')
    approved = sum(1 for d in changes
                   if (d / 'proposal.md').is_file()
                   and re.search(r'^## Approval', (d / 'proposal.md').read_text(),
                                 re.M))
    return len(changes), approved


def risk_tone(status: str) -> str:
    word = status.split()[0].rstrip(':').lower()
    return {'mitigated': 'success', 'open': 'warning', 'accepted': 'info',
            'closed': 'muted', 'withdrawn': 'muted'}.get(word, 'neutral')


def trust_artifacts(root, cfg, registry, risks, releases):
    items = [
        ('Requirements registry', 'docs/traceability/requirements-registry.md',
         f'{len(registry)} IDs', 'success',
         'Every requirement with its stable ID, allocated at proposal time and '
         'never reused.'),
        ('Traceability matrix', 'docs/traceability/matrix.md',
         'Generated', 'info',
         'Requirement → spec → tests → commits, regenerated from repository '
         'state by tools/trace.py.'),
        ('Risk register', 'docs/security/risk-register.md',
         f'{len(risks)} risks', 'info',
         'Known risks with likelihood, impact, and what protects against each '
         'one now.'),
        ('Threat model', 'docs/security/threat-model.md',
         'Living', 'success',
         'STRIDE analysis of every attack surface, updated in the same change '
         'that adds one.'),
        ('Dependency (SOUP) register', 'docs/security/soup-register.md',
         'Living', 'success',
         'Every third-party dependency with its role, license, and review '
         'state.'),
        ('Known-anomalies register', 'docs/security/known-anomalies.md',
         'Living', 'neutral',
         'Oddities and accepted imperfections, recorded instead of quietly '
         'ignored.'),
    ]
    cards = []
    for name, rel, status, tone, note in items:
        if not (root / rel).is_file():
            fail(f'trust-center artifact missing from repository: {rel}')
        cards.append({'name': name, 'path': rel, 'status': status,
                      'tone': tone, 'note': note,
                      'href': f'{cfg["site"]["repo_url"]}/blob/main/{rel}'})
    cards.append({'name': 'Release records', 'path': 'GitHub Releases',
                  'status': f'{len(releases)} published', 'tone': 'success',
                  'note': 'Every tagged release with its notes — the same text '
                          'as the CHANGELOG entry it mirrors.',
                  'href': cfg['site']['releases_url']})
    return cards


def governance_artifacts(root, cfg):
    """Process/governance card row (FRG-SITE-004) — existence-checked."""
    n_changes, n_approved = archive_approvals(root)
    items = [
        ('Development-process spec', 'openspec/specs/dev-process/spec.md',
         'Governing', 'success',
         'The process rules themselves — spec before code, stable IDs, tagged '
         'tests, review gates — written as requirements like everything else.'),
        ('Commit standard & merge gates', 'docs/process/commit-standard.md',
         'Enforced by hooks', 'success',
         'Commit format with mandatory requirement trailers, and the checklist '
         'every change passes before it merges.'),
        ('Archived change proposals', 'openspec/changes/archive/',
         f'{n_approved} of {n_changes} approved', 'success',
         'Every completed change with its proposal, design, tasks, and the '
         'recorded owner approval that let implementation begin.'),
        ('User & admin manual', 'docs/manual/',
         'Synced per change', 'info',
         'Documentation is updated in the same change that alters behavior — '
         'a change declares its manual impact or states why there is none.'),
        ('Repository history scan', 'docs/security/history-scan.md',
         'Recorded', 'neutral',
         'History hygiene: what was checked for secrets and residue before the '
         'repository went public.'),
    ]
    cards = []
    for name, rel, status, tone, note in items:
        target = root / rel.rstrip('/')
        if not (target.is_file() or target.is_dir()):
            fail(f'governance artifact missing from repository: {rel}')
        blob = 'tree' if rel.endswith('/') else 'blob'
        cards.append({'name': name, 'path': rel, 'status': status,
                      'tone': tone, 'note': note,
                      'href': f'{cfg["site"]["repo_url"]}/{blob}/main/{rel.rstrip("/")}'})
    return cards


# What is deliberately NOT claimed, each citing the committed doc that records
# the deferral (FRG-SITE-004 absence section — rendered inside
# <section data-absence>, the one region exempt from the banned-phrase scan).
ABSENCES = [
    ('External penetration test',
     'None has been performed. The roadmap schedules the penetration-test '
     'decision — whether, scope, and by whom — at the 1.0 go-live milestone.',
     'docs/roadmap.md'),
    ('CI-enforced quality gates',
     'Test suites and consistency checks run at every merge gate on the '
     'operator’s machine, not in CI; the Pages deploy workflow is the '
     'only CI.',
     'docs/process/commit-standard.md'),
    ('Live dependency-advisory review',
     'Dependency inventory is complete and mechanically verified, but '
     'advisory scanning (pip-audit, npm audit) is deferred until '
     'network-connected CI exists.',
     'docs/security/soup-register.md'),
    ('Formal CAPA process',
     'There is no corrective-and-preventive-action log; the known-anomalies '
     'register is the nearest current artifact.',
     'docs/security/known-anomalies.md'),
]


# --- rendering ---------------------------------------------------------------

PAGES = [('index.html', 'Overview'), ('method.html', 'The Method'),
         ('timeline.html', 'Timeline'), ('trust.html', 'Trust Center'),
         ('product.html', 'Product')]


def template(name: str) -> Template:
    return Template(read_text(SITE_DIR / 'templates' / name, f'template {name}'))


def nav_html(active: str) -> str:
    out = []
    for href, label in PAGES:
        cls = 'nav-link active' if href == active else 'nav-link'
        out.append(f'<a class="{cls}" href="{href}">{esc(label)}</a>')
    return ''.join(out)


def chip(text: str, tone: str = 'neutral') -> str:
    return f'<span class="chip chip-{tone}">{esc(text)}</span>'


def render_pages(root, cfg, registry, matrix, releases, risks, license_name):
    site = cfg['site']
    traced, live = coverage(registry, matrix)
    ex = exemplar_card(cfg, registry, matrix)
    artifacts = trust_artifacts(root, cfg, registry, risks, releases)
    governance = governance_artifacts(root, cfg)
    cov = coverage_breakdown(registry, matrix)

    base = template('base.html')
    mark_svg = read_text(root / 'docs/assets/foragerr-mark.svg', 'logo mark')

    def page(active, title, content):
        return base.substitute(
            title=esc(title), description=esc(site['description']),
            nav=nav_html(active), repo_url=esc(site['repo_url']),
            mark=mark_svg, license=esc(license_name), content=content)

    stats = [
        (str(live), 'requirements in the registry'),
        (f'{cov["implemented_tested"]} of {cov["implemented_total"]}',
         'implemented requirements have tagged tests'),
        (str(len(releases)), 'tagged releases'),
        (str(len(risks)), 'risks tracked in the register'),
    ]
    stat_tiles = ''.join(
        f'<div class="stat"><div class="stat-v">{esc(v)}</div>'
        f'<div class="stat-l">{esc(l)}</div></div>' for v, l in stats)

    pillars = [
        ('01', 'A requirement registry',
         'Every behavior foragerr is meant to have is written down first, with '
         'a stable ID. IDs are allocated in the registry when a change is '
         'proposed, and a commit hook rejects any commit citing an ID that '
         'is not registered.',
         ['IDs allocated before code', 'Never reused or renumbered',
          'Enforced by the commit hook']),
        ('02', 'End-to-end traceability',
         'Each requirement links to the spec that defines it, the tagged tests '
         'that prove it, and the commits that built it. The matrix is '
         'regenerated from repository state — spec headings, test tags, commit '
         'trailers — and inconsistencies fail the run.',
         ['Requirement → spec → test → commit', 'Generated, not asserted',
          'Gaps are visible, not hidden']),
        ('03', 'Per-change review gates',
         'The owner approves every proposal before implementation begins, and '
         'no change merges until its gate passes: the full test suite green, '
         'traceability and dependency checks at zero, and a multi-angle review '
         'of the diff.',
         ['Owner approval before code', 'Full suite + consistency checks',
          'Multi-angle diff review']),
        ('04', 'Release records',
         'Every tagged release carries the same four artifacts: a CHANGELOG '
         'entry citing the requirements it moved, an annotated tag, the pushed '
         'history, and a GitHub Release. Tags are immutable — a mistake gets a '
         'new patch release, never a moved tag.',
         ['CHANGELOG + tag + GitHub Release', 'Requirement refs in every entry',
          'Tags are immutable']),
    ]

    def pillar_cards(compact: bool) -> str:
        out = []
        for n, title, body, points in pillars:
            pts = (''.join(f'<span class="pill">{esc(p)}</span>' for p in points)
                   if compact else
                   ''.join(f'<div class="pillar-point"><span>—</span>'
                           f'<span>{esc(p)}</span></div>' for p in points))
            out.append(
                f'<div class="card pillar"><div class="pillar-head">'
                f'<span class="pillar-n">{n}</span>'
                f'<span class="pillar-title">{esc(title)}</span></div>'
                f'<p>{esc(body)}</p><div class="pillar-points">{pts}</div></div>')
        return ''.join(out)

    trace_rows = ''.join(
        f'<div class="trace-row"><span class="trace-k">{esc(k)}</span>'
        f'<span class="trace-v">{esc(v)}</span></div>' for k, v in ex['rows'])

    overview = template('overview.html').substitute(
        exemplar_id=esc(ex['id']), exemplar_title=esc(ex['title']),
        trace_rows=trace_rows, stat_tiles=stat_tiles,
        pillar_cards=pillar_cards(compact=True),
        matrix_url=esc(f'{site["repo_url"]}/blob/main/docs/traceability/matrix.md'),
        n_releases=str(len(releases)))

    lifecycle = [
        ('01', 'Propose', 'An OpenSpec change defines the requirements; their '
                          'IDs are allocated in the registry.'),
        ('02', 'Approve', 'The owner approves every proposal before '
                          'implementation begins.'),
        ('03', 'Implement', 'Claude builds against the spec on a branch; '
                            'main stays green.'),
        ('04', 'Prove', 'Every requirement gets automated tests tagged with '
                        'its ID.'),
        ('05', 'Gate', 'Full test suite, traceability and dependency checks, '
                       'and a multi-angle review of the diff.'),
        ('06', 'Release', 'A CHANGELOG entry, an annotated tag, and a GitHub '
                          'Release — minted together.'),
    ]
    lifecycle_html = ''.join(
        f'<div class="life-step"><div class="pillar-n">{n}</div>'
        f'<div class="life-title">{esc(t)}</div><div class="life-body">'
        f'{esc(b)}</div></div>' for n, t, b in lifecycle)

    method = template('method.html').substitute(
        lifecycle=lifecycle_html, pillar_cards=pillar_cards(compact=False))

    groups, seen = [], {}
    for r in releases:
        minor = '.'.join(r['version'].split('.')[:2]) + '.x'
        if minor not in seen:
            seen[minor] = {'label': minor, 'entries': []}
            groups.append(seen[minor])
        seen[minor]['entries'].append(r)

    def release_entry(r):
        intro = ''.join(f'<p>{inline_md(p)}</p>' for p in r['intro'])
        sections = ''.join(
            f'<div class="rel-section"><h4>{esc(s["name"])}</h4><ul>' +
            ''.join(f'<li>{inline_md(i)}</li>' for i in s['items']) +
            '</ul></div>' for s in r['sections'])
        ids = r['ids']
        shown = ''.join(f'<span class="frg-id">{esc(i)}</span>' for i in ids[:8])
        more = (f'<span class="frg-more">+{len(ids) - 8} more</span>'
                if len(ids) > 8 else '')
        idrow = (f'<div class="rel-ids">{shown}{more}</div>' if ids else '')
        return (f'<div class="card release"><div class="rel-head">'
                f'<span class="rel-version">{esc(r["version"])}</span>'
                f'<span class="rel-date">{esc(r["date"])}</span></div>'
                f'<div class="rel-body">{intro}{sections}{idrow}</div></div>')

    timeline_groups = ''.join(
        f'<section class="tl-group"><h2 class="tl-minor">{esc(g["label"])}</h2>'
        + ''.join(release_entry(r) for r in g['entries']) + '</section>'
        for g in groups)

    timeline = template('timeline.html').substitute(
        n_releases=str(len(releases)), timeline_groups=timeline_groups,
        releases_url=esc(site['releases_url']))

    def artifact_card_html(items):
        return ''.join(
            f'<a class="card artifact" href="{esc(a["href"])}">'
            f'<div class="artifact-head"><span class="artifact-name">'
            f'{esc(a["name"])}</span>{chip(a["status"], a["tone"])}</div>'
            f'<div class="artifact-path">{esc(a["path"])}</div>'
            f'<div class="artifact-note">{esc(a["note"])}</div></a>'
            for a in items)

    artifact_cards = artifact_card_html(artifacts)
    governance_cards = artifact_card_html(governance)

    coverage_tiles = ''.join(
        f'<div class="cov-tile"><div class="cov-v">{esc(v)}</div>'
        f'<div class="cov-l">{esc(l)}</div><div class="cov-note">{esc(n)}</div></div>'
        for v, l, n in [
            (f'{cov["implemented_tested"]} of {cov["implemented_total"]}',
             'implemented requirements with tagged tests',
             'The traceability check fails the merge gate on any implemented '
             'requirement without one — this cannot silently regress.'),
            (str(cov['approved_total']),
             'approved, not yet built',
             'Backlog requirements carry no tests by definition; they are '
             'specified, awaiting implementation.'),
            (f'{cov["active_tested"]} of {cov["active_total"]}',
             'process rules machine-tested',
             'The rest of the process rules are enforced by git hooks and the '
             'merge-gate checklist rather than the test suite.'),
        ])

    absence_items = []
    for name, body, cite in ABSENCES:
        if not (root / cite).is_file():
            fail(f'absence citation missing from repository: {cite}')
        absence_items.append(
            f'<div class="card absence-item"><div class="absence-name">'
            f'{esc(name)}</div><p>{esc(body)}</p>'
            f'<a class="artifact-path" '
            f'href="{esc(site["repo_url"])}/blob/main/{esc(cite)}">'
            f'{esc(cite)}</a></div>')

    risk_rows = ''.join(
        f'<tr><td class="mono">{esc(r["id"])}</td><td>{esc(r["desc"])}</td>'
        f'<td>{esc(r["l"])}</td><td>{esc(r["i"])}</td>'
        f'<td>{chip(r["status"].split()[0], risk_tone(r["status"]))}</td></tr>'
        for r in risks)

    trust = template('trust.html').substitute(
        artifact_cards=artifact_cards, governance_cards=governance_cards,
        coverage_tiles=coverage_tiles, absence_items=''.join(absence_items),
        risk_rows=risk_rows, n_risks=str(len(risks)),
        register_url=esc(f'{site["repo_url"]}/blob/main/docs/security/risk-register.md'))

    features = [
        ('Import & rename', 'Point it at an existing collection; it scans, '
         'matches, and renames in place — non-destructive by default.'),
        ('Metadata matching', 'Matches issues against ComicVine and groups '
         'series into their franchises.'),
        ('Have / missing', 'Per-series issue tracking that knows which issues '
         'you own and which are missing.'),
        ('Gap fill', 'Newznab indexers with SABnzbd or the built-in downloader '
         'fetch the issues you are missing.'),
        ('Serve over OPDS', 'Read on any OPDS client — an iPad over Tailscale. '
         'No built-in reader by design.'),
        ('Sources you own', 'Connect a Humble Bundle account and import the '
         'DRM-free purchases you already own.'),
    ]
    feature_cards = ''.join(
        f'<div class="card feature"><div class="feature-title">{esc(t)}</div>'
        f'<p>{esc(b)}</p></div>' for t, b in features)

    shots = []
    for fname, caption in PRODUCT_SHOTS:
        if not (root / 'docs/readme-assets' / fname).is_file():
            fail(f'product screenshot missing: docs/readme-assets/{fname}')
        shots.append(f'<figure class="shot"><img src="assets/shots/{fname}" '
                     f'alt="{esc(caption)}" loading="lazy">'
                     f'<figcaption>{esc(caption)}</figcaption></figure>')

    product = template('product.html').substitute(
        feature_cards=feature_cards, shots=''.join(shots), mark=mark_svg)

    titles = {
        'index.html': site['title'],
        'method.html': 'The Method — foragerr',
        'timeline.html': 'Timeline — foragerr',
        'trust.html': 'Trust Center — foragerr',
        'product.html': 'Product — foragerr',
    }
    bodies = {'index.html': overview, 'method.html': method,
              'timeline.html': timeline, 'trust.html': trust,
              'product.html': product}
    return {name: page(name, titles[name], bodies[name]) for name in bodies}


# --- truthfulness scans (FRG-SITE-004/006) -----------------------------------

ABSENCE_SECTION_RE = re.compile(r'<section[^>]*\bdata-absence\b.*?</section>',
                                re.S)


def scan_output(pages: dict, banned: list, license_name: str, repo_url: str):
    for name, content in pages.items():
        # The one dedicated absence section may name missing artifacts to state
        # they do not exist (FRG-SITE-004); positive claims elsewhere still fail.
        if len(ABSENCE_SECTION_RE.findall(content)) > 1:
            fail(f'more than one absence section in {name}')
        low = ABSENCE_SECTION_RE.sub('', content).lower()
        for phrase in banned:
            if phrase.lower() in low:
                fail(f'banned phrase {phrase!r} found in {name}')
    if license_name not in pages['index.html']:
        fail('footer license claim missing from built output')
    for name, content in pages.items():
        if repo_url not in content:
            fail(f'repository link missing from {name}')


# --- main --------------------------------------------------------------------

def build(root: Path, out: Path) -> None:
    cfg = load_config()
    registry = load_registry(root)
    matrix = load_matrix(root)
    releases = load_changelog(root)
    tags = git_tags(root)
    risks = load_risks(root)
    license_name = license_family(root)
    banned = load_banned()

    untagged = [r['version'] for r in releases if r['version'] not in tags]
    if untagged:
        fail(f'CHANGELOG releases without a git tag: {", ".join(untagged)}')

    pages = render_pages(root, cfg, registry, matrix, releases, risks,
                         license_name)
    scan_output(pages, banned, license_name, cfg['site']['repo_url'])

    # Everything validated — only now touch the output directory.
    if out.exists():
        shutil.rmtree(out)
    (out / 'static').mkdir(parents=True)
    (out / 'assets' / 'shots').mkdir(parents=True)
    for name, content in pages.items():
        (out / name).write_text(content, encoding='utf-8')
    shutil.copy(SITE_DIR / 'static' / 'site.css', out / 'static' / 'site.css')
    shutil.copy(root / 'docs/assets/foragerr-mark.svg',
                out / 'assets' / 'foragerr-mark.svg')
    for fname, _ in PRODUCT_SHOTS:
        shutil.copy(root / 'docs/readme-assets' / fname,
                    out / 'assets' / 'shots' / fname)
    print(f'site built: {len(pages)} pages, {len(releases)} releases, '
          f'{len(registry)} requirements → {out}')


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--root', type=Path,
                    default=SITE_DIR.parent, help='repository root')
    ap.add_argument('--out', type=Path, default=None,
                    help='output directory (default <root>/_site)')
    args = ap.parse_args()
    root = args.root.resolve()
    build(root, (args.out or root / '_site').resolve())


if __name__ == '__main__':
    main()
