#!/usr/bin/env python3
"""Regenerate the traceability matrix (FRG-PROC-005).

Cross-references, from repository state alone:
  - docs/traceability/requirements-registry.md   (allocation table)
  - openspec/specs/*/spec.md                     (requirement headings)
  - git log Refs: trailers                       (implementing commits)
  - test files containing requirement-ID tags    (pytest req markers / ID strings)

Writes docs/traceability/matrix.md and exits non-zero on inconsistencies
(registry/spec mismatch, duplicate IDs), so it can gate CI later.
"""
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ID_RE = re.compile(r'FRG-[A-Z]{2,5}-\d{3}')


def registry_rows():
    rows = {}
    for line in (ROOT / 'docs/traceability/requirements-registry.md').read_text().splitlines():
        cells = [c.strip() for c in line.strip().strip('|').split('|')]
        if len(cells) >= 5 and ID_RE.fullmatch(cells[0]):
            rows[cells[0]] = {'title': cells[1], 'spec': cells[2], 'status': cells[3], 'milestone': cells[4]}
    return rows


def spec_ids():
    found = defaultdict(list)
    for spec in sorted((ROOT / 'openspec/specs').glob('*/spec.md')):
        for m in re.finditer(r'^### Requirement: (FRG-[A-Z]{2,5}-\d{3})', spec.read_text(), re.M):
            found[m.group(1)].append(spec.parent.name)
    return found


def open_change_delta_ids():
    """Requirement headings declared in OPEN change deltas (not the archive).

    A `proposed` registry row is expected to live here rather than in a
    baseline spec — the delta is synced to baseline when the change merges.
    """
    found = set()
    for spec in (ROOT / 'openspec/changes').glob('*/specs/*/spec.md'):
        if 'archive' in spec.parts:
            continue
        for m in re.finditer(r'^### Requirement: (FRG-[A-Z]{2,5}-\d{3})', spec.read_text(), re.M):
            found.add(m.group(1))
    return found


def spec_milestones():
    """Per-requirement `**Milestone**:` fields from the baseline specs."""
    fields = {}
    for spec in sorted((ROOT / 'openspec/specs').glob('*/spec.md')):
        blocks = re.split(r'(^### Requirement: FRG-[A-Z]{2,5}-\d{3})', spec.read_text(), flags=re.M)
        rid = None
        for block in blocks:
            m = re.match(r'### Requirement: (FRG-[A-Z]{2,5}-\d{3})', block)
            if m:
                rid = m.group(1)
                continue
            if rid:
                mm = re.search(r'\*\*Milestone\*\*:\s*(\S+)', block)
                if mm:
                    fields[rid] = mm.group(1)
                rid = None
    return fields


def commit_refs():
    out = subprocess.run(
        ['git', 'log', '--format=%h%x00%s%x00%(trailers:key=Refs,valueonly)', '--no-merges'],
        capture_output=True, text=True, cwd=ROOT).stdout
    refs = defaultdict(list)
    for entry in out.strip().split('\n'):
        parts = entry.split('\x00')
        if len(parts) < 3:
            continue
        sha, subject, trailer = parts[0], parts[1], parts[2]
        for rid in ID_RE.findall(trailer):
            refs[rid].append(sha)
    return refs


def test_tags():
    tags = defaultdict(list)
    for pattern in (
        'backend/tests/**/*.py',
        'frontend/src/**/*.test.*',
        'frontend/src/**/*.spec.*',
        'e2e/tests/**/*.spec.*',  # FRG ids in Playwright test titles (FRG-PROC-010)
        'extension/tests/**/*.test.mjs',  # FRG ids in node:test titles (companion extension)
    ):
        for f in ROOT.glob(pattern):
            for rid in set(ID_RE.findall(f.read_text(errors='ignore'))):
                tags[rid].append(str(f.relative_to(ROOT)))
    return tags


def main():
    reg = registry_rows()
    specs = spec_ids()
    refs = commit_refs()
    tests = test_tags()
    problems = []

    for rid, places in specs.items():
        if len(places) > 1:
            problems.append(f'{rid} appears in multiple specs: {places}')
        if rid not in reg:
            problems.append(f'{rid} in spec {places} but not in registry')
    delta_ids = open_change_delta_ids()
    for rid, row in reg.items():
        if row['status'] in ('withdrawn',):
            if rid in specs:
                problems.append(f'{rid} is withdrawn but still present in spec {specs[rid]}')
        elif rid not in specs:
            if row['status'] == 'proposed' and rid in delta_ids:
                continue  # lives in an open change delta; baseline sync happens at merge
            problems.append(f'{rid} ({row["status"]}) in registry but in no spec or open change delta')

    for rid, ms in spec_milestones().items():
        if rid in reg and ms != reg[rid]['milestone']:
            problems.append(
                f'{rid} milestone drift: spec says {ms}, registry says {reg[rid]["milestone"]}'
            )

    lines = ['# Traceability Matrix', '',
             '_Generated by `tools/trace.py` (FRG-PROC-005). Do not edit by hand._', '',
             '| ID | Status | Milestone | Spec | Tests | Commits |',
             '|----|--------|-----------|------|-------|---------|']
    counts = defaultdict(int)
    for rid in sorted(reg):
        row = reg[rid]
        # Sorted: Path.glob discovery order is filesystem-dependent, and an
        # unordered join makes regeneration reshuffle cells run-to-run
        # (FRG-PROC-005 requires stable regeneration).
        t = ', '.join(sorted(tests.get(rid, []))) or '—'
        c = ', '.join(refs.get(rid, [])[:6]) or '—'
        s = specs.get(rid, ['—'])[0]
        lines.append(f'| {rid} | {row["status"]} | {row["milestone"]} | {s} | {t} | {c} |')
        counts[row['status']] += 1
        if row['status'] in ('implemented', 'verified'):
            if rid not in tests:
                problems.append(f'{rid} is {row["status"]} but has no tagged test')
            if rid not in refs:
                problems.append(f'{rid} is {row["status"]} but no commit references it')

    lines += ['', '## Summary', '',
              ' · '.join(f'{k}: {v}' for k, v in sorted(counts.items())),
              f' · total: {len(reg)}', '']
    if problems:
        lines += ['## Gaps', ''] + [f'- {p}' for p in problems] + ['']
    (ROOT / 'docs/traceability/matrix.md').write_text('\n'.join(lines))

    print(f'{len(reg)} registry rows · {len(specs)} spec requirements · '
          f'{sum(len(v) for v in refs.values())} commit refs · {len(tests)} tested IDs')
    for p in problems:
        print(f'GAP: {p}', file=sys.stderr)
    sys.exit(1 if problems else 0)


if __name__ == '__main__':
    main()
